language: ruby
rvm:
  - 2.5.1
services: postgres
before_script:
  - rm config/database.yml
  - cp config/database.travis.yml config/database.yml
  - sudo -u postgres psql -c 'create database maslow_test;'
  - bundle exec rake db:migrate
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
